### ISSUE TITLE
[PE-D][Tester B] Increment parameter not optional but stated to be optional

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-4/tp#100]
From the user guide:
`incr INDEX [tr/TRANSACTION_COUNT_INCREMENT_AMOUNT]`

Square brackets indicate optional parameters, but the program fails to execute the command if `TRANSACTION_COUNT_INCREMENT_AMOUNT` is not provided.

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: chuakid/ped#3

**Comment by jjiayyingtt** [comment]
Done
