### ISSUE TITLE
[PE-D][Tester B] Increment amount limits differ from user guide

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103-F10-4/tp#96]
From the user guide:
`The increment amount must be an integer greater than zero.

From the program: 

![image.png](https://raw.githubusercontent.com/chuakid/ped/main/files/acf74d05-3bd2-4572-a4ce-12c8e10d2e8f.png)

On entering `incr 1 tr/0` the program proceeds with no error.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: chuakid/ped#1

**Comment by jjiayyingtt** [comment]
Confusing description, seems like the error message is correctly outputted.
