### ISSUE TITLE
[PE-D][Tester B] Decrement command format incorrect 

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103-F10-4/tp#97]
![image.png](https://raw.githubusercontent.com/chuakid/ped/main/files/88a22435-6748-456e-8bf7-376ce9ecb783.png)

Should be `decr` instead.

-------------
Labels: `type.DocumentationBug` `severity.VeryLow`
original: chuakid/ped#2

**Comment by jjiayyingtt** [comment]
Done
